image: harbor.blacklake.tech/infra/java11_ci_runtime:latest

variables:
  APP_NAME: "openapi-sdk"

stages:
  - build
  - lint

deploymaven:
  stage: build
  only:
    - dev
    - /^feat/.*/
    - /^release-.*/
    - /^experimental.*/
  allow_failure: true
  when: manual
  script:
    - mvn -version
    - /ci/scripts/build_backend_api.sh
    - mvn -version

sonar:
  image: harbor.blacklake.tech/az/sonar-cli-runtime:latest
  stage: lint
  allow_failure: true
  only:
    - dev
    - /^feat/.*/
    - /^release-.*/
    - /^experimental.*/
  script:
    - /ci/scripts/check_sonar.sh

