image: harbor.blacklake.tech/infra/java11_ci_runtime:latest

variables:
  APP_NAME: "openapi-sdk"

stages:
  - build
  - deploy
  - lint

build-service:
  stage: build
  only:
    - dev
    - feature
    - /^feat/.*/
    - feature
    - /^release-.*/
  script:
    - /ci/scripts/build_backend_service.sh

build-api:
  stage: build
  only:
    - dev
    - /^feat/.*/
    - feature
    - /^release-.*/
  when: manual
  allow_failure: true
  script:
    - /ci/scripts/build_backend_api.sh

deploy:
  stage: deploy
  only:
    - dev
    - /^feat/.*/
    - feature
    - /^release-.*/
  script:
    - /ci/scripts/deploy2.sh

sonar:
  image: harbor.blacklake.tech/az/sonar-cli-runtime:latest
  stage: lint
  allow_failure: true
  only:
    - dev
    - feature
    - /^feat/.*/
    - feature
    - /^release-.*/
  script:
    - /ci/scripts/check_sonar.sh
